# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Push a new beta build to TestFlight"
  lane :beta do
    tests
    increment_build_number(build_number: number_of_commits)
    get_certificates(
      development: true,
      username: "victorpanitz@gmail.com"
    )
    sigh(force: true)
    enable_automatic_code_signing
    gym(scheme: "SortingAlgorithms", export_method: "development")
    upload_to_testflight
  end

  desc "Run current tests"
  lane :tests do
    run_tests(scheme: "SortingAlgorithmsTests")
  end

end
